### ISSUE TITLE
Error occurred 

### ISSUE THREAD

**Issue by Iristallite** [Emiougus/TriggerRemap#1]
I try to launch the app, but this garbage happened
[string "?"]:23: cannot load font file
![image](https://user-images.githubusercontent.com/28459742/87856470-f4575f00-c8f9-11ea-89dd-5631566bf3fe.jpg)

**Comment by Emiougus** [comment]
Keep spamming X to restart until it works, working on a fix for this

**Comment by Emiougus** [comment]
Haven't been able to replicate this error after I made a few changes, so I'm not really able to test if I've fixed it or not. I've attached a VPK with updated code would you be able to download that for me and see if it's fixed your problem? If you're still having it that is.


[TriggerRemap.zip](https://github.com/Emiougus/TriggerRemap/files/4943225/TriggerRemap.zip)

**Comment by Iristallite** [comment]
fixed the problem
